version: "3.8"

services:
  mysql_db:
    build:
      dockerfile: mysql.Dockerfile
    restart: always
    cap_add:
      - SYS_NICE
    # volumes:
    #   - "./setup.sql:/docker-entrypoint-initdb.d"
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: todoapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost
    networks:
      backend:

  api:
    build: ./api 
    container_name: api
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      backend:

  myblog:
    build: ./client
    container_name: client
    ports:
      - '5173:5173'
    volumes:
    - ./client:/app
    - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

networks:
  backend: